[package]
name = "panicshutdown"
version = "0.2.2"
description = "a minimal utility for an almost instant safe-ish shutdown"
repository = "https://codeberg.org/quixaq/panicshutdown"
license = "GPL-3.0-or-later"
keywords = ["cli", "sysrq", "linux", "proc", "shutdown"]
categories = ["command-line-utilities"]
readme = "README.md"
edition = "2024"

[dependencies]
nix = { version = "0.31.3", features = [ "user", "fs", "mount", "reboot" ] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
strip = true
